export default {
"setVolume":"Establecer volumen",
"play":"",
"stop":"Detener",
"pause":"Pausar",
"resume":"Resumir",
"nextSong":"Proxima cancion",
"previousSong":"Anterior cancion",
"setGenre":"Establecer genero",
"getPlaylist":"Obtener lista de reproduccion",
"open":"Abrir",
"close":"Cerrar",
"turnOn":"Prender",
"turnOff":"Apagar",
"setColor":"Establecer color",
"setBrightness":"Establecer brillo",
"setTemperature":"Establecer temperatura",
"setHeat":"Establecer fuente de calor",
"setGrill":"Establecer modo grill",
"setConvection":"Establecer modo de conveccion",
"setMode":"Establecer modo",
"setVerticalSwing":"Establecer swing vertical",
"setHorizontalSwing":"Establecer swing horizontal",
"setFanSpeed":"Establecer velocidad del ventilador",
"lock":"Trabar",
"unlock":"Destrabar",
"changeSecurityCode":"Cambiar codigo de seguridad",
"armStay":"Prender en modo casa",
"armAway":"Prender en modo regular",
"disarm":"Apagar",
"start":"Comenzar",
"dock":"Volver al dock",
"setLocation":"Establecer locacion",
"setFreezerTemperature":"Establecer temperatura del freezer",
};
